services:
    mysql:
        container_name: some_sql
        image: mysql
        environment:
            - MYSQL_DATABASE=jwt
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3305:3306"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - spring-boot-network
    spring-boot-app:
        container_name: spring-demo
        image: docker/demo
        ports:
            - "8088:8080"
        networks:
            - spring-boot-network

volumes:
    mysql:

networks:
    spring-boot-network:
        driver: bridge